/** Every visible player string: an instruction or a state. Nothing else. */
const en = {
  start: "Start",
  continue: "Continue",
  back: "Back",
  skip: "Skip",
  send: "Send",
  sending: "Sending…",
  retry: "Retry",
  review: "Check your answers",
  notAnswered: "—",
  yes: "Yes",
  no: "No",
  privacy: "Privacy",
  resume: "Resume",
  paused: "Paused",
  soundOn: "Sound on",
  soundOff: "Sound off",
  volume: "Volume",
  standardForm: "Use standard form",
  hint: "Click to shoot · Esc for menu",
  typeHere: "Type your answer",
  emailHere: "name@company.com",
  previewBadge: "Preview · nothing is saved",
  demoBadge: "Demo · nothing is saved",
  savedNothing: "Nothing was saved.",
  backToWorkspace: "Back to workspace",
  unavailable: "This form isn’t available.",
  fixAnswers: "Check your answers before sending.",
  retryNote: "Retry sends the same answers once.",
  noGraphics: "3D isn’t available here, so this is the standard form.",
  noPointer: "Mouse capture isn’t available here, so this is the standard form.",
  lockAgain: "Click Resume again.",
  decrease: "Decrease",
  increase: "Increase",
};

export type Copy = typeof en;

const sl: Copy = {
  start: "Začni",
  continue: "Naprej",
  back: "Nazaj",
  skip: "Preskoči",
  send: "Pošlji",
  sending: "Pošiljam…",
  retry: "Poskusi znova",
  review: "Preveri odgovore",
  notAnswered: "—",
  yes: "Da",
  no: "Ne",
  privacy: "Zasebnost",
  resume: "Nadaljuj",
  paused: "Premor",
  soundOn: "Zvok vklopljen",
  soundOff: "Zvok izklopljen",
  volume: "Glasnost",
  standardForm: "Uporabi običajen obrazec",
  hint: "Klikni za strel · Esc za meni",
  typeHere: "Vpiši odgovor",
  emailHere: "ime@podjetje.si",
  previewBadge: "Predogled · nič se ne shrani",
  demoBadge: "Demo · nič se ne shrani",
  savedNothing: "Nič ni bilo shranjeno.",
  backToWorkspace: "Nazaj v aplikacijo",
  unavailable: "Ta obrazec ni na voljo.",
  fixAnswers: "Pred oddajo preveri odgovore.",
  retryNote: "Ponovitev varno pošlje iste odgovore.",
  noGraphics: "3D tu ni na voljo, zato je to običajen obrazec.",
  noPointer: "Zajem miške tu ni na voljo, zato je to običajen obrazec.",
  lockAgain: "Klikni Nadaljuj še enkrat.",
  decrease: "Zmanjšaj",
  increase: "Povečaj",
};

export const copyFor = (locale: string): Copy => (locale === "sl" ? sl : en);
